name: elola
description: A fun Spanish nouns game.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.1
  provider: ^5.0.0
  intl: ^0.17.0
  # defuncart
  flutter_core_logic:
    git:
      url: https://github.com/defuncart/flutter_core_logic
      ref: main
  # third party
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  mobx: ^2.0.0-nullsafety.5
  flutter_mobx: ^2.0.0-nullsafety.3
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_tts: ^3.0.0
  grouped_buttons:
    git:
      url: https://github.com/defuncart/fork_grouped_buttons
      ref: feature/null-safety
  outline_material_icons:
    git:
      url: https://github.com/Ahmadre/outline_material_icons
  flutter_validate_unicode: 
    path: packages/flutter_validate_unicode/
  flutter_html: ^2.0.0-nullsafety.0
  material_design_icons_flutter: ^5.0.5955-rc.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  # flappy_translator:
  #   git:
  #     url: https://github.com/smartnsoft/FlappyTranslator/
  #     ref: feature/basic-plurals-support
  flutter_pseudolocalizor: ^0.4.0
  hive_generator: ^1.0.0
  mobx_codegen: ^2.0.0-nullsafety.2

dependency_overrides:
  build: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/database/

# settings for flappy_translator package
flappy_translator:
  input_file_path: "assets_dev/loca/loca-PSEUDO.csv"
  output_dir: "lib"
  file_name: "localizations"
  class_name: "AppLocalizations"
  delimiter: ";"
  start_index: 1
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false
  expose_get_text: true

# settings for flutter_pseudolocalizor package
flutter_pseudolocalizor:
  input_filepath: "assets_dev/loca/loca.csv"
  replace_base: false
  use_brackets: true
  text_expansion_ratio: null
  languages_to_generate:
    - de
    - pl
  csv_settings:
    delimiter: ";"
    column_index: 1
  patterns_to_ignore:
    - '¿El o La?'
    - '%(\S*?)\$[ds]'
    - '\|(.*)\|'
