name: elola
description: A fun Spanish nouns game.
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.5
  provider: ^4.0.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  auto_size_text: ^2.1.0
  flutter_tts: ^0.9.1
  grouped_buttons: ^1.0.4
  outline_material_icons: ^0.1.1
  flutter_validate_unicode: 
    path: packages/flutter_validate_unicode/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  flappy_translator:
    git:
      url: https://github.com/defuncart/flappy_translator/
      ref: feature/get-text-option
  flutter_pseudolocalizor: ^0.2.0
  hive_generator: ^0.7.0+2
  mobx_codegen: ^1.0.3

# temp workaround hive + beta issue
dependency_overrides:
  dartx: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/database/

# settings for flappy_translator package
flappy_translator:
  input_file_path: "assets_dev/loca/loca-PSEUDO.csv"
  output_dir: "lib"
  file_name: "localizations"
  class_name: "AppLocalizations"
  delimiter: ";"
  start_index: 1
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false
  expose_get_text: true

# settings for flutter_pseudolocalizor package
flutter_pseudolocalizor:
  input_filepath: "assets_dev/loca/loca.csv"
  replace_base: false
  use_brackets: true
  text_expansion_ratio: null
  languages_to_generate:
    - de
    - pl
  csv_settings:
    delimiter: ";"
    column_index: 1
  patterns_to_ignore:
    - '¿El o La?'
    - '%(\S*?)\$[ds]'
