import 'dart:async';

import 'package:flutter/material.dart';

/// This class is generated by the flappy_translator package
/// Please do not change anything manually in this file, instead re-generate it when changes are available
class AppLocalizations {
  static String get appTitle => _getText('appTitle');

  static String get generalPlay => _getText('generalPlay');

  static String get generalContinue => _getText('generalContinue');

  static String get homeTabViewAllNouns => _getText('homeTabViewAllNouns');

  static String get settingsTabDarkModeLabel =>
      _getText('settingsTabDarkModeLabel');

  static String get settingsTabLanguageLabel =>
      _getText('settingsTabLanguageLabel');

  static String get generalCommingSoon => _getText('generalCommingSoon');

  static String get categoryfoodFruit => _getText('categoryfoodFruit');

  static String get categoryfoodVegetable => _getText('categoryfoodVegetable');

  static String get homeTabNounOfTheDayLabel =>
      _getText('homeTabNounOfTheDayLabel');

  static String get homeTabFavoritesLabel => _getText('homeTabFavoritesLabel');

  static String get homeTabFavoritesViewAllLabel =>
      _getText('homeTabFavoritesViewAllLabel');

  static String get homeTabFavoritesAddSomeLabel =>
      _getText('homeTabFavoritesAddSomeLabel');

  static Map<String, String> _localizedValues;

  static Map<String, String> _enValues = {
    'appTitle': '¿El o La?',
    'generalPlay': 'Play',
    'generalContinue': 'Continue',
    'homeTabViewAllNouns': 'View all nouns',
    'settingsTabDarkModeLabel': 'Dark Mode',
    'settingsTabLanguageLabel': 'Language',
    'generalCommingSoon': 'Coming Soon!',
    'categoryfoodFruit': 'Fruit',
    'categoryfoodVegetable': 'Vegetables',
    'homeTabNounOfTheDayLabel': 'Noun of the day',
    'homeTabFavoritesLabel': 'Favorites',
    'homeTabFavoritesViewAllLabel': 'View all',
    'homeTabFavoritesAddSomeLabel':
        'Having difficulties with some nouns? Add them as favorites!',
  };

  static Map<String, String> _deValues = {
    'appTitle': '[ ¿El o La? Ääüßö ]',
    'generalPlay': '[ Play Üü ]',
    'generalContinue': '[ Cöntinüe Ääẞẞ ]',
    'homeTabViewAllNouns': '[ View all nöüns äẞÄßöÜ ]',
    'settingsTabDarkModeLabel': '[ Dark Möde äÜÄÄÄ ]',
    'settingsTabLanguageLabel': '[ Langüage ÜäöÜ ]',
    'generalCommingSoon': '[ Cöming Söön! ÖẞÄÖÖ ]',
    'categoryfoodFruit': '[ Früit ẞÜẞ ]',
    'categoryfoodVegetable': '[ Vegetaßles äÖÖẞÄ ]',
    'homeTabNounOfTheDayLabel': '[ Nöün öf the day ÖÄööÄß ]',
    'homeTabFavoritesLabel': '[ Favörites ÄüÖÖÜ ]',
    'homeTabFavoritesViewAllLabel': '[ View all äßÜÄ ]',
    'homeTabFavoritesAddSomeLabel':
        '[ Having difficülties with söme nöüns? Ädd them as favörites! ööÄäÜÄääẞüÜẞẞßöüßü ]',
  };

  static Map<String, String> _plValues = {
    'appTitle': '[ ¿El o La? ÓŻŚźę ]',
    'generalPlay': '[ Płay Ąź ]',
    'generalContinue': '[ Ćóńtińuę ŚŹźŹ ]',
    'homeTabViewAllNouns': '[ Vięw ałł ńóuńś śśŁęĘę ]',
    'settingsTabDarkModeLabel': '[ Dark Módę ążżŻĄ ]',
    'settingsTabLanguageLabel': '[ Łańguagę ÓĘĄŃ ]',
    'generalCommingSoon': '[ Ćómińg Śóóń! ĆóÓęŹ ]',
    'categoryfoodFruit': '[ Fruit ĆźŹ ]',
    'categoryfoodVegetable': '[ Vęgętabłęś ółĆŻą ]',
    'homeTabNounOfTheDayLabel': '[ Ńóuń óf thę day óćĆńŻż ]',
    'homeTabFavoritesLabel': '[ Favóritęś ŻÓÓŹŹ ]',
    'homeTabFavoritesViewAllLabel': '[ Vięw ałł óŹÓŻ ]',
    'homeTabFavoritesAddSomeLabel':
        '[ Havińg diffićułtięś with śómę ńóuńś? Ądd thęm aś favóritęś! ŚżĄŃĄłśóśŃŚńŹĆĄŃćĘ ]',
  };

  static Map<String, Map<String, String>> _allValues = {
    'en': _enValues,
    'de': _deValues,
    'pl': _plValues,
  };

  AppLocalizations(Locale locale) {
    _locale = locale;
    _localizedValues = null;
  }

  static Locale _locale;

  static String _getText(String key) {
    return _localizedValues[key] ?? '** $key not found';
  }

  static Locale get currentLocale => _locale;

  static String get currentLanguage => _locale.languageCode;

  static String getText(String key) => _getText(key);

  static Future<AppLocalizations> load(Locale locale) async {
    final translations = AppLocalizations(locale);
    _localizedValues = _allValues[locale.toString()];
    return translations;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
    Locale('de'),
    Locale('pl'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<AppLocalizations> load(Locale locale) => AppLocalizations.load(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
