name: emoji_generator
description: A simply library which can be used to generate emojis from names.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  flutter_emoji: ^2.2.1+1
  emojis:
    git:
      url: https://github.com/defuncart/emojis
      ref: bugfix/search-with-invalid-emoji-name

dev_dependencies:
  flutter_test:
    sdk: flutter
